App\Domain\Event\Event:
  type: entity
  table: events
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    slug:
      type: string
    location:
      type: string
    description:
      type: text
    eventType:
      type: string
      column: type
    priceAmount:
      type: integer
      column: price_amount
    priceCurrencyCode:
      type: string
      column: price_currency